### ISSUE TITLE
keycloak object properties such as keycloak.authenticated are not reactive

### ISSUE THREAD

**Issue by Powersource** [react-keycloak/react-keycloak#116]
When I use e.g. `keycloak.authenticated` (`keycloak` gotten from the hook), things will not rerender even if `authenticated` gets a new value. (as far as I can tell?)

I was thinking I could maybe solve this in my project by maybe sort of creating a `useState` alternative for `authenticated`, that somehow refreshes itself whenever the provider's `onEvent` callback runs. But I think this should probably be something that's built into react-keycloak since it will be a common problem/usecase.

**Comment by Powersource** [comment]
Could it maybe be enough to also export `isAuthenticated` (which already is react state) [here](https://github.com/react-keycloak/react-keycloak/blob/master/packages/core/src/provider.tsx#L212) (and in the other related exports)?

**Comment by stahlmanDesign** [comment]
I am also confused by this but maybe I don't understand how hooks work well enough.

Originally I thought `const keycloak = useKeycloak()` and then `const { token } = keycloak` would give me the updated token like changed state when the tokens are refreshed.

In other words, when `onKeycloakEvent` fires with an `onAuthRefreshSuccess` , I expected useKeycloak hooks in other components to provide the new token and refreshToken. But those instances contain the original token info and do not seem to update.

To access the updated tokens I now pass them as props, but I don't know if this is the intended way to do it.

**Comment by stahlmanDesign** [comment]
OK, I think the problem is that my components are not updating. If I set a timer and force them to update, keycloak has the new token.

This is probably by design and good in that we don't want the page to re-render and reload just because there's a new token. 

Instead, when save data button clicked, the token can be fetched at that moment so we don't use an invalid token when calling the server.

**Comment by panz3r** [comment]
Hi @Powersource and @stahlmanDesign ,

Thanks for your feedback, as @stahlmanDesign pointed out the `keycloak` instance returned by the `useKeycloak` hook behaves much like a value returned by the `useRef` hook (details [here](https://reactjs.org/docs/hooks-reference.html#useref)) so when accessing one of the instance props they always return the latest value but when changing they do not trigger re-renders.

In a previous version (`react-keycloak/web` pre-`3.2.0`) a change in the tokens value would trigger a global re-render of the app and raised issue #97 , after a recent change this behaviour has been updated (because of the reason highlighted above) and the only things which triggers a re-render is a change in the `authentication` state (when tokens get removed after an error event) because I believe that is the only thing that must be used to conditionally render parts of a UI (I didn't see any use-case that required printing out the current user tokens).

Let me know if this helps you or if you have any further question.

**Comment by Powersource** [comment]
Yeah I mostly need the `authenticated` (rendering log in vs log out). And I noticed I was using 3.0.0 so I updated to 3.4.0 to get e.g. this commit https://github.com/react-keycloak/react-keycloak/commit/3ffa66dcd88927b0247bdaacade08f62cfd77ed2 but that didn't really seem to help. I also tried downgrading to keycloak-js 9 as this issue suggested https://github.com/react-keycloak/react-keycloak/issues/108 but that didn't seem to change much either.

Now when I'm using the app and parts are getting rerendered I am getting console.logged that `initialized` = false, even if it very shortly before that logged that it was true, and also logged the token that it found, so I'm not sure how it can be uninitialized again.

I guess I'm not sure if the title of this issue is correct anymore. But something isn't working as I want it to around the user's authentication status :/

Idk if it'll help but here's the PR I'm working on, for context https://github.com/Edgeryders-Participio/realities/pull/121

**Comment by panz3r** [comment]
Hi @Powersource ,

> Now when I'm using the app and parts are getting rerendered I am getting console.logged that initialized = false, even if it very shortly before that logged that it was true, and also logged the token that it found, so I'm not sure how it can be uninitialized again.

This is actually a really strange behaviour and I wasn't able to reproduce it with the example projects, the only reason that the `initialized` flag is reset should be a change in the Keycloak instance passed to the 'KeycloakProvider'.

Another thing you can try is to use the `LoadingComponent` prop of `KeycloakProvider` and pass in a component to be rendered while the `Keycloak` instance is getting initialised.

**Comment by Powersource** [comment]
For now I'm not going to focus on getting this fixed. We got a recommendation to use a more generic OIDC client instead of one that just works with keycloak so I'm gonna be trying that this week. More info https://github.com/Edgeryders-Participio/realities/issues/132

**Comment by Powersource** [comment]
PS. probably a good idea to mention in the readme that if people just want auth then they could probably use any OIDC compatible client

**Comment by ChristianDavis** [comment]
change in authentication state in keycloak still doesn't re-render the hook. Strange design decision

**Comment by jsphstls** [comment]
I'm glad I found this thread, I thought for sure that the hook would cause a re-render. React docs advise not to prevent re-renders especially when it comes to hooks since one of the strengths of React is that multiple re-renders can still produce a single update to the DOM.

Instead of changing the behaviour of a hook, an alternate hook could be provided with a different name.

**Comment by silenzium** [comment]
Not nice, but maybe helpful:
The following workaround forces react to do a render on token changes.

```
const App = () => {
    const [, setTokenUpdateCount] = useState(0);
    
    const onUpdateToken = useCallback(() => {
        setTokenUpdateCount((value) => value + 1);
    }, []);
    
    return (
        <ReactKeycloakProvider
            authClient={keycloak}
            initOptions={initOptions}
            onTokens={onUpdateToken}
        >
            <YourComponentRelyingOnUseKeycloak/>
        </ReactKeycloakProvider>
    );
}
```
